# Generated by Django 5.0.6 on 2024-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_name', models.CharField(max_length=100, verbose_name='Filer Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('reason_for_complaint', models.TextField(verbose_name='Reason for Complaint')),
            ],
        ),
    ]
