# Generated by Django 5.0.6 on 2024-05-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_vendor'),
        ('home', '0002_pointofinterest'),
    ]

    operations = [
    ]
