# Generated by Django 5.0.6 on 2024-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_pass"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color code for the route", max_length=7
                    ),
                ),
                (
                    "points",
                    models.ManyToManyField(
                        related_name="routes", to="home.pointofinterest"
                    ),
                ),
            ],
        ),
    ]
